include: package:very_good_analysis/analysis_options.yaml

# Reglas Lint y documentación, véase en https://dart.dev/tools/linter-rules.
linter:
  rules:
    public_member_api_docs: false

    sort_pub_dependencies: false