name: eos_mobile
description: EOS Mobile
# La siguiente línea evita que el paquete se publique accidentalmente en
# pub.dev usando `flutter pub publish`. Esto es preferible para paquetes privados.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado de gestión de aplicaciones Flutter basado en el patrón BLoC
  bloc: ^8.1.3

  # Plugin de Flutter para acceder a la cámara
  camera: ^0.10.5+9

  # Verifica el estado de la conexión a Internet
  connectivity_plus: ^5.0.2

  # Conjunto de funciones de hashing criptográficas
  crypto: ^3.0.3

  # Íconos Cupertino para iOS
  cupertino_icons: ^1.0.2

  # Generador de JWT (Json Web Token)
  dart_jsonwebtoken: ^2.13.0

  # Programación funcional en Dart
  dartz: ^0.10.1

  # HTTP Requests, Interceptors, Transformers, etc.
  dio: ^5.4.1

  # Widget para bordear con puntos un contenedor en Flutter
  dotted_border: ^2.1.0

  # Widget de búsqueda de Flutter con dropdown
  dropdown_button2: ^2.3.9

  # Encriptacion
  encrypt: ^5.0.3

  # Simplifica la comparación de objetos en Dart
  equatable: ^2.0.5

  # Diseña temas basados en Material Design
  flex_color_scheme: ^7.3.1

  # Animaciones de Flutter
  flutter_animate: ^4.5.0

  # Widgets Flutter basados en el patrón de diseño BLoC
  flutter_bloc: ^8.1.4

  # Manejo de modos de visualización en Flutter
  flutter_displaymode: ^0.6.0

  # Plugin para cambiar los íconos de la aplicación Flutter
  flutter_launcher_icons: ^0.13.1

  # Splash screen nativo en Flutter
  flutter_native_splash: ^2.3.10

  # API para almacenamiento de datos en almacenamiento seguro
  flutter_secure_storage: ^9.0.0

  # Muestra imágenes SVG
  flutter_svg: ^2.0.9

  # Agrega espacios entre widgets en Flutter
  gap: ^3.0.1

  # Localizador de servicios directos
  get_it: ^7.6.7

  # Mixins para `watch` los servicios registrados con GetIt
  get_it_mixin: ^4.2.2

  # Router declarativo para Flutter
  go_router: ^13.2.0

  # Internacionalización, formateo de fechas, números, etc
  intl: ^0.19.0

  # Recortar una imagen
  image_cropper: ^5.0.1

  # Selecciona imágenes de galería y permite tomar nuevas fotografías
  image_picker: ^1.0.7

  # Define anotaciones utilizadas por `json_serializable`
  json_annotation: ^4.8.1

  # JSON Web Tokens
  jwt_decode: ^0.3.1

  # Imprime hermosos registros en el log.
  logger: ^2.1.0

  # Renderiza animaciones de After Effects en Flutter
  lottie: ^3.0.0

  # Base de datos local persistente NoSQL
  objectbox: ^2.5.1

  # Plugin de ObjectBox para trabajar con Flutter
  objectbox_flutter_libs: any

  # Abre archivos con resultados de cadenas en Flutter
  open_file: ^3.3.2

  # Consultar información sobre el paquete de la aplicación
  package_info_plus: ^5.0.1

  # Obtiene información sobre rutas de archivos
  path: ^1.8.3

  # Obtiene ubicaciones de uso común en los sitemas de archivos
  path_provider: ^2.1.2

  # Wrapper de InheritedWidget para reutilizaciones globales
  provider: ^6.1.1

  # Generador de código para cliente Dio
  retrofit: ^4.1.0

  # Leer/Escribir pares clave-valor en el sistema del usuario
  shared_preferences: ^2.2.2

  # Efecto de esqueleto de carga en Flutter
  shimmer: ^3.0.0

  # Indicadores de página animados
  smooth_page_indicator: ^1.1.0

  # Widget para capturar firmas en Flutter
  syncfusion_flutter_signaturepad: ^24.2.9

  # Plugin de Flutter para lanzar URL
  url_launcher: ^6.2.4

  # Generador y analizador UUID para Dart
  uuid: ^4.3.3

  # Widget WebView en Android e iOS
  webview_flutter: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Testing de BLoCs
  bloc_test: ^9.1.6

  # Generador de código y compilación modular
  build_runner: ^2.4.8

  # Linters de Flutter
  flutter_lints: ^3.0.1

  # Genera código convertido a JSON
  json_serializable: ^6.6.2

  # Generador de ObjectBox
  objectbox_generator: any

  # Generador de retrofit
  retrofit_generator: ^8.1.0

  # Reglas de lint para Dart y Flutter
  very_good_analysis: ^5.1.0

# Native Flutter Splash Screen
flutter_native_splash:
  color: '#fafafa'
  image: assets/marketing/app-icon-1024.png

  android_12:
    color: '#fafafa'
    image: assets/marketing/app-icon-1024.png

  web: false

# ejecutar: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: assets/marketing/app-icon-1024.png
  remove_alpha_ios: true
  android: true
  ios: true
  min_sdk_android: 21

# La siguiente sección es específica para los paquetes Flutter.
flutter:
  # La siguiente línea asegura que la fuente Material Icons esté
  # incluida con la aplicación, para que podamos utilizar los iconos en
  # la clase Material Icons.
  uses-material-design: true

  generate: true

  assets:
    - assets/icons/
    - assets/images/backgrounds/
    - assets/images/errors/
    - assets/images/logo/
    - assets/images/pages/
    - assets/images/welcome/
    - assets/lottie/

  fonts:
    - family: Font72
      fonts:
        - asset: assets/fonts/72-Light.ttf
          weight: 200
        - asset: assets/fonts/72-Regular.ttf
          weight: 400
        - asset: assets/fonts/72-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/72-Bold.ttf
          weight: 700
        - asset: assets/fonts/72-Black.ttf
          weight: 800
