name: eos_mobile
description: EOS Mobile
# La siguiente línea evita que el paquete se publique accidentalmente en
# pub.dev usando `flutter pub publish`. Esto es preferible para paquetes privados.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Biblioteca de gestión de estados predictivo
  bloc: ^8.1.3
  # Íconos estilo iOS
  cupertino_icons: ^1.0.2
  # Programación funcional en Dart
  dartz: ^0.10.1
  # Peticiones HTTP, Interceptores, Transformadores, etc
  dio: ^5.4.1
  # Buscador de Flutter con dropdown
  dropdown_search: ^5.0.6
  # Simplificar comparación de objetos de Dart
  equatable: ^2.0.5
  # Diseñar temas basado en Material Design
  flex_color_scheme: ^7.3.1
  # Widgets Flutter basados en el patrón de diseño BLoC
  flutter_bloc: ^8.1.4
  # Splash screen nativo en Flutter
  flutter_native_splash: ^2.3.10
  # API para almacenar datos en almacenamiento seguro
  flutter_secure_storage: ^9.0.0
  # Mostrar imágenes SVG
  flutter_svg: ^2.0.9
  # Mostrar Toasts en Flutter
  fluttertoast: ^8.2.4
  # Pack de íconos de FontAwesome
  font_awesome_flutter: ^10.7.0
  # Agregar gaps a widgets de Flutter
  gap: ^3.0.1
  # Localizador directo de servicios
  get_it: ^7.6.7
  # Mixins para `watch` los servicios registrados con GetIt
  get_it_mixin: ^4.2.2
  # Router declarativo para Flutter
  go_router: ^13.2.0
  # Internacionalización, formateo de fechas, números, etc
  intl: ^0.19.0
  # Seleccionar imágenes de galería y tomar nuevas fotografías
  image_picker: ^1.0.7
  # Define anotaciones usados por `json_serializable`
  json_annotation: ^4.8.1
  # Renderiza animaciones de After Effects en Flutter
  lottie: ^3.0.0
  # Buscador basado en el diseño Material de Google
  material_floating_search_bar_2: ^0.5.0
  # Abrir archivos con resultados de cadena en Flutter
  open_file: ^3.3.2
  # Obtener ubicaciones de uso común en los sitemas de archivos
  path_provider: ^2.1.2
  # Wrapper de InheritedWidget para reutilizaciones globales
  provider: ^6.1.1
  # Generador de código para cliente Dio
  retrofit: ^4.1.0
  # Leer/Escribir key-value pairs en el sistema del usuario
  shared_preferences: ^2.2.2
  # Efecto de brillo en Flutter
  shimmer: ^3.0.0
  # Indicadores de página animados
  smooth_page_indicator: ^1.1.0
  # Plugin de Flutter para lanzar URL
  url_launcher: ^6.2.4
  connectivity_plus: ^5.0.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Testing de BLoCs
  bloc_test: ^9.1.6
  # Generador de código y compilación modular
  build_runner: ^2.4.8
  # Linters de Flutter
  flutter_lints: ^2.0.0
  # Genera código convertido a JSON
  json_serializable: ^6.6.2
  # Generador de retrofit
  retrofit_generator: ^8.1.0
  # Reglas de lint para Dart y Flutter
  very_good_analysis: ^5.1.0

# Native Flutter Splash Screen
flutter_native_splash:
  color: '#fafafa'
  image: assets/marketing/app-icon-1024.png

  android_12:
    color: '#fafafa'
    image: assets/marketing/app-icon-1024.png

  web: false


# La siguiente sección es específica para los paquetes Flutter.
flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/icons/
    - assets/images/backgrounds/
    - assets/images/errors/
    - assets/images/logo/
    - assets/images/pages/
    - assets/images/welcome/
    - assets/lottie/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

    - family: OpenSansEmoji
      fonts:
        - asset: assets/fonts/OpenSansEmoji.ttf
